services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shadcn_api_prod
    environment:
      - NODE_ENV=production
      - DB_HOST=172.17.0.1
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - DB_PORT=5432
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: shadcn_nginx_prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - api
    restart: unless-stopped
