version: "3.9"

services:
  api:
    image: node:22.16.0
    container_name: shadcn_api
    working_dir: /app
    command: sh -c "npm install && node server.js"
    volumes:
      - ./server:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=172.17.0.1
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
      - DB_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
  react:
    image: node:20-alpine
    container_name: shadcn_react
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: shadcn_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - api
